# Generated by Django 4.2.2 on 2023-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0002_article_feed_delete_feedentry_article_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
