# Generated by Django 4.2.2 on 2023-07-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0009_article_guid_article_rss_feed_name_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
