# Generated by Django 4.2.2 on 2023-07-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0010_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
