# Generated by Django 4.2.2 on 2023-07-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0011_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
        migrations.AddField(
            model_name='feed',
            name='source_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
