# Generated by Django 4.2.2 on 2023-07-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0012_remove_feed_image_feed_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_image',
            field=models.URLField(blank=True),
        ),
    ]
