# Generated by Django 4.2.2 on 2023-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0013_article_source_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
